# Generated by Django 4.0.3 on 2022-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0003_rename_subject_todaytasks_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaytasks',
            name='contents',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todaytasks',
            name='importance',
            field=models.IntegerField(null=True),
        ),
    ]
