# Generated by Django 4.0.3 on 2022-04-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0005_alter_todaytasks_contents_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodayTasks',
            new_name='Task',
        ),
    ]
